# Generated by Django 4.2 on 2026-03-09 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barkod')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın'), ('unisex', 'Unisex')], default='unisex', max_length=20, verbose_name='Cinsiyet')),
                ('size', models.CharField(choices=[('XS', 'Çok Küçük'), ('S', 'Küçük'), ('M', 'Medium'), ('L', 'Büyük'), ('XL', 'Çok Büyük'), ('XXL', '2XL')], max_length=5, verbose_name='Beden')),
                ('color', models.CharField(max_length=50, verbose_name='Renk')),
                ('price_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maliyet Fiyatı')),
                ('price_selling', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('reorder_level', models.PositiveIntegerField(default=10, verbose_name='Yeniden Sipariş Seviyesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Mağaza Adı')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Mağaza',
                'verbose_name_plural': 'Mağazalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Çalışan'), ('manager', 'Mağaza Müdürü'), ('admin', 'Admin')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.store', verbose_name='Mağaza')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış'), ('adjustment', 'Ayarlama'), ('return', 'İade')], max_length=20, verbose_name='Hareket Türü')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referans')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Ürün')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.store', verbose_name='Mağaza')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Miktar')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Son Kontrol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product', verbose_name='Ürün')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.store', verbose_name='Mağaza')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'store'], name='inventory_s_product_56a85c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'store'], name='inventory_s_product_14f0f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'store')},
        ),
    ]
