# Generated by Django 4.2 on 2026-03-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_sku_f85905_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_selling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='İndirim'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fiyat'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeAge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beden/Yaş'),
        ),
        migrations.AddField(
            model_name='product',
            name='specCode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Özel Kod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Barkod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['specCode'], name='inventory_p_specCod_1eb148_idx'),
        ),
    ]
