# Generated by Django 4.2 on 2026-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['code'], 'verbose_name': 'Mağaza', 'verbose_name_plural': 'Mağazalar'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_sku_f85905_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_product_14f0f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inventory_s_product_56a85c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_selling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='İndirim'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fiyat'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeAge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beden/Yaş'),
        ),
        migrations.AddField(
            model_name='product',
            name='specCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel Kod'),
        ),
        migrations.AddField(
            model_name='stock',
            name='barcode',
            field=models.CharField(default='', max_length=50, verbose_name='Barkod'),
        ),
        migrations.AddField(
            model_name='stock',
            name='store_code',
            field=models.CharField(default='', max_length=10, verbose_name='Mağaza Kodu'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='barcode',
            field=models.CharField(default='', max_length=50, verbose_name='Barkod'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='store_code',
            field=models.CharField(default='', max_length=10, verbose_name='Mağaza Kodu'),
        ),
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Mağaza Kodu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kullanıcı ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Barkod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('barcode', 'store_code')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['specCode'], name='inventory_p_specCod_1eb148_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['barcode', 'store_code'], name='inventory_s_barcode_48d04e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['barcode', 'store_code'], name='inventory_s_barcode_7b496f_idx'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store',
        ),
    ]
