# Generated by Django 4.2 on 2026-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_store_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.CharField(max_length=50, verbose_name='Barkod'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store_code',
            field=models.CharField(max_length=10, verbose_name='Mağaza Kodu'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mağaza Kodu'),
        ),
    ]
