# Generated by Django 4.2 on 2026-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_inventory_p_sku_f85905_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel Kod'),
        ),
    ]
