# Generated by Django 4.2 on 2026-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_store_id_alter_stock_barcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['store_code', 'location', 'barcode'], 'verbose_name': 'Stok', 'verbose_name_plural': 'Stoklar'},
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_barcode_48d04e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(choices=[('warehouse', 'Depo'), ('shelf', 'Reyon')], default='warehouse', max_length=20, verbose_name='Yer'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_location',
            field=models.CharField(blank=True, choices=[('warehouse', 'Depo'), ('shelf', 'Reyon')], max_length=20, null=True, verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.CharField(choices=[('warehouse', 'Depo'), ('shelf', 'Reyon')], default='warehouse', max_length=20, verbose_name='Yer'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.CharField(blank=True, choices=[('warehouse', 'Depo'), ('shelf', 'Reyon')], max_length=20, null=True, verbose_name='Nereye'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış'), ('adjustment', 'Ayarlama'), ('return', 'İade'), ('transfer', 'Transfer')], max_length=20, verbose_name='Hareket Türü'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('barcode', 'store_code', 'location')},
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['barcode', 'store_code', 'location'], name='inventory_s_barcode_6eaad1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['store_code', 'location'], name='inventory_s_store_c_b04dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store_code', 'location'], name='inventory_s_store_c_eaba62_idx'),
        ),
    ]
