# Generated by Django 4.2 on 2026-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_speccode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['code'], 'verbose_name': 'Mağaza', 'verbose_name_plural': 'Mağazalar'},
        ),
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Mağaza Kodu'),
        ),
    ]
