# Generated by Django 4.2 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_store_options_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kullanıcı ID'),
        ),
    ]
