# Generated by Django 4.2 on 2026-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='store_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Mağaza Kodu'),
        ),
    ]
