# Generated by Django 4.2 on 2026-04-13 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile_user_id_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='shelf_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reyon Stoku'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Depo Stoku'),
        ),
    ]
