# Generated by Django 4.2 on 2026-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile_store_code'),
    ]

    operations = [
        # Remove the old store FK that still references integer Store.id
        migrations.RemoveField(
            model_name='userprofile',
            name='store',
        ),
    ]
