# Generated by Django 4.2 on 2026-06-12 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_fix_userprofile_store_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=50, unique=True, verbose_name='Koli Barkodu')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('closed', 'Kapalı'), ('sent', 'Gönderildi')], default='open', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış Tarihi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('receiver_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_received', to='inventory.store', verbose_name='Alan Mağaza')),
                ('sender_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_sent', to='inventory.store', verbose_name='Gönderen Mağaza')),
            ],
            options={
                'verbose_name': 'Koli',
                'verbose_name_plural': 'Koliler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, verbose_name='Barkod')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miktar')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ekleme Tarihi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Ürün')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shipment', verbose_name='Koli')),
            ],
            options={
                'verbose_name': 'Koli Ürünü',
                'verbose_name_plural': 'Koli Ürünleri',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'barcode'], name='inventory_s_shipmen_7162b9_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipment_code'], name='inventory_s_shipmen_bcbcac_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sender_store', 'status'], name='inventory_s_sender__5538ea_idx'),
        ),
    ]
