# Generated by Django 4.2 on 2026-04-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_shelf_quantity_stock_warehouse_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mağaza Kodu'),
        ),
    ]
