# Generated by Django 4.2 on 2026-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_shipment_shipmentitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kabul Tarihi'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('closed', 'Kapalı'), ('sent', 'Gönderildi'), ('received', 'Kabul Edildi')], default='open', max_length=20, verbose_name='Durum'),
        ),
    ]
