# Generated by Django 4.2 on 2026-04-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stock_quantity'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Eski foreign key constraint'ini sil
                "ALTER TABLE inventory_stock DROP CONSTRAINT IF EXISTS inventory_stock_store_id_fk CASCADE;",
                # store_id sütununu sil
                "ALTER TABLE inventory_stock DROP COLUMN IF EXISTS store_id;",
                # Yeni store_code sütunu ekle (VARCHAR)
                "ALTER TABLE inventory_stock ADD COLUMN store_code VARCHAR(10) NOT NULL DEFAULT 'M01';",
                # Yeni foreign key constraint'ini ekle (inventory_store(code) referansı ile)
                "ALTER TABLE inventory_stock ADD CONSTRAINT inventory_stock_store_code_fk FOREIGN KEY (store_code) REFERENCES inventory_store(code) ON DELETE CASCADE;",
            ],
            reverse_sql=[
                # Reverse işlemler
                "ALTER TABLE inventory_stock DROP CONSTRAINT IF EXISTS inventory_stock_store_code_fk CASCADE;",
                "ALTER TABLE inventory_stock DROP COLUMN IF EXISTS store_code;",
                "ALTER TABLE inventory_stock ADD COLUMN store_id BIGINT NOT NULL DEFAULT 1;",
            ]
        ),
    ]
